
// Projects data
export const projects = [
    // ── GROUP 1: Detailed Case Studies (1–3) ─────────────────────────────────
    {
        id: 1,
        slug: 'national-real-estate-erp',
        name: 'National Real Estate ERP Implementation',
        shortName: 'Real Estate ERP',
        type: 'Enterprise Software',
        badge: 'Multi-State',
        badgeColor: 'bg-blue-100 text-blue-700',
        image: '/National_Real_Estate_ERP_Visualization_card.png',
        summary: 'Developed a centralized ERP system for 120+ construction sites across 6 states. Modules: Procurement, Vendor Management, Site Reporting.',
        duration: '18 Months',
        scope: [
            'Multi-state ERP deployment across 6 Indian states',
            'Centralized procurement & automated vendor workflows',
            'Real-time site reporting and management dashboards',
            'Role-based access control (RBAC) and security auditing',
            'Integration with legacy accounting and site systems',
        ],
        tech: ['React.js (TypeScript)', 'Django Microservices', 'PostgreSQL + Redis', 'AWS Cloud Infrastructure', 'Docker & CI/CD Pipeline', 'RESTful API Architecture'],
        outcomes: [
            { label: 'Cost Visibility', value: '+35%' },
            { label: 'Reporting Speed', value: '60% Faster' },
            { label: 'Site Coverage', value: '120+ Locations' },
            { label: 'Audit Compliance', value: '100%' },
        ],
        category: 'detailed',
    },
    {
        id: 2,
        slug: 'smart-site-monitoring',
        name: 'SmartSite Monitoring System',
        shortName: 'SmartSite Monitoring',
        type: 'Technology / IoT',
        badge: 'AI-Powered',
        badgeColor: 'bg-emerald-100 text-emerald-700',
        image: '/SmartSite%20Monitoring%20System.jpg.jpeg',
        summary: 'IoT-based workforce attendance & progress tracking for infrastructure projects.',
        duration: 'Ongoing Support',
        scope: [
            'IoT-enabled biometric attendance tracking at site level',
            'Geo-tagged workforce monitoring and safety alerts',
            'Real-time construction progress visualization',
            'Centralized productivity analytics and reporting',
            'Hardware-software integration for smart gate entry',
        ],
        tech: ['Industrial IoT Sensors', 'Biometric Middleware', 'React.js Dashboard', 'Python / Node.js Engine', 'Real-Time Data Sync', 'Cloud Security'],
        outcomes: [
            { label: 'Workforce Accuracy', value: '99.9%' },
            { label: 'Proxy Attendance', value: 'Eliminated' },
            { label: 'Site Visibility', value: '24/7 Live' },
            { label: 'Admin Efficiency', value: '+40%' },
        ],
        category: 'detailed',
    },
    {
        id: 3,
        slug: 'government-infrastructure-digitization',
        name: 'Government Infrastructure Digitization',
        shortName: 'Govt. Digitization',
        type: 'Government',
        badge: 'Public Sector',
        badgeColor: 'bg-violet-100 text-violet-700',
        image: '/Government%20Infrastructure%20Digitization.png',
        summary: 'Digitized project tracking dashboards for public infrastructure development.',
        duration: 'Milestone-based',
        scope: [
            'Public sector project lifecycle digitization',
            'Citizen-facing transparency and status portals',
            'Inter-departmental milestone tracking and approvals',
            'Compliance automation for government standards',
            'Audit-ready electronic document management (EDM)',
        ],
        tech: ['GovCloud (MeitY Approved)', 'React.js', 'Enterprise Django', 'PostgreSQL', 'Secure OAuth 2.0', 'Encryption at Rest'],
        outcomes: [
            { label: 'Paperwork Reduction', value: '85%' },
            { label: 'Tracking Latency', value: 'Near-zero' },
            { label: 'Process Speed', value: '+50%' },
            { label: 'Public Accountability', value: 'Enhanced' },
        ],
        category: 'detailed',
    },

    // ── GROUP 2: Structured Engagements (4–7) ──────────────────────────────────
    {
        id: 4,
        slug: 'enterprise-vendor-automation',
        name: 'Enterprise Vendor Automation Platform',
        shortName: 'Vendor Automation',
        type: 'Enterprise Software',
        badge: 'Custom ERP',
        image: '/Enterprise%20Vendor%20Automation%20Platform.png',
        summary: 'Automated vendor billing and compliance system for large construction groups.',
        scope: [
            'End-to-end vendor onboarding and KYC automation',
            'Dynamic billing engine with auto-reconciliation',
            'Real-time compliance and document tracking',
            'Automated payment scheduling and tax auditing',
        ],
        tech: ['React.js', 'Node.js', 'PostgreSQL', 'Tally API', 'SAP B1 Integration', 'AWS EC2'],
        outcomes: [
            '45% faster billing cycle',
            'Zero compliance errors',
            'Automated workflows',
            'Improved reconciliation',
        ],
        category: 'grid',
    },
    {
        id: 5,
        slug: 'multi-state-workforce-deployment',
        name: 'Multi-State Workforce Deployment Project',
        shortName: 'Workforce Deployment',
        type: 'Operations',
        badge: 'Pan-India',
        image: '/Multi-State%20Workforce%20Deployment%20Project.png',
        summary: 'Deployed 800+ site staff across 45 active construction zones.',
        scope: [
            'Nationwide recruitment and placement framework',
            'Skill-based automated resource allocation',
            'Real-time workforce performance monitoring',
            'Statutory compliance and payroll integration',
        ],
        tech: ['Fleet Management App', 'Cloud Data Sync', 'GPS Tracking', 'HR Portal', 'Helpdesk Support'],
        outcomes: [
            '800+ Staff Deployed',
            'Zero Deployment Lag',
            'Centralized Monitoring',
            'SLA-bound Support',
        ],
        category: 'grid',
    },
    {
        id: 6,
        slug: 'construction-billing-software',
        name: 'Construction Billing & Cost Control Software',
        shortName: 'Billing & Cost Control',
        type: 'Software / ERP',
        badge: 'ERP Solution',
        image: '/Construction%20Billing%20&%20Cost%20Control%20Software.png',
        summary: 'Real-time material usage and cost monitoring application.',
        scope: [
            'Bill of Quantities (BoQ) digital integration',
            'Real-time material consumption and wastage tracking',
            'Budget alert system for procurement overruns',
            'Cloud-based ledger for multi-site cost auditing',
        ],
        tech: ['Python / Django', 'React.js', 'PostgreSQL', 'AWS Infrastructure', 'Analytics Engine'],
        outcomes: [
            'Reduced cost leakage',
            'Accurate budget tracking',
            '70% less manual entry',
            'Profitability insights',
        ],
        category: 'grid',
    },
    {
        id: 7,
        slug: 'housing-project-management',
        name: 'Large-Scale Housing Project Management System',
        shortName: 'Housing Management',
        type: 'Real Estate / Software',
        badge: '15,000+ Units',
        image: '/Real_Estate__Housing_Projects.png',
        summary: 'Digital progress tracking for 15,000+ residential units.',
        scope: [
            'Unit-level construction milestone management',
            'Subcontractor coordination and quality audits',
            'Stakeholder transparency and reporting portal',
            'Customer handover and snagging automation',
        ],
        tech: ['Mobile Audit App', 'Central Dashboard', 'Cloud Reporting', 'RESTful APIs', 'Security Layer'],
        outcomes: [
            '15,000+ Units Managed',
            '50% lower project delays',
            'Enhanced stakeholder trust',
            'Real-time snagging fix',
        ],
        category: 'grid',
    },

    // ── GROUP 3: National Scale (8–10) ────────────────────────────────────
    {
        id: 8,
        slug: 'warehouse-logistics-automation',
        name: 'Warehouse & Logistics Automation',
        shortName: 'Logistics Automation',
        type: 'Logistics / Industry 4.0',
        badge: 'Industry 4.0',
        image: '/Warehouse&Logistics%20Automation.png',
        summary: 'Integrated supply chain tracking system for building materials.',
        scale: 'Multi-Location Warehouses',
        duration: 'Ongoing Managed Services',
        workforce: 'Supply Chain Engineering Team',
        impact: 'Full Material Traceability (99.9%)',
        phases: [
            'Warehouse Infrastructure Audit',
            'Supply Chain Logic Design',
            'Smart Inventory System Deployment',
            'Field-level Operational Training',
        ],
        states: ['Telangana', 'Andhra Pradesh', 'Tamil Nadu'],
        accent: 'blue',
        scope: [
            'Supply chain automation with multi-location syncing',
            'Real-time inventory tracking and smart stock alerts',
            'Dispatch and logistics monitoring for building materials',
            'Barcode and QR-based automated asset tracking',
            'Centralized warehouse performance dashboards',
        ],
        tech: ['RFID/Barcode Integration', 'Cloud Inventory Engine', 'Logistics API Gateways', 'Power BI Analytics', 'Secure Edge Computing'],
        outcomes: [
            'Real-time inventory sync',
            'Optimized dispatch flow',
            'Zero stock-out events',
            '99% tracking accuracy',
        ],
        category: 'executive',
    },
    {
        id: 9,
        slug: 'corporate-it-infrastructure',
        name: 'Corporate IT Infrastructure Setup',
        shortName: 'Corporate IT Setup',
        type: 'IT Infrastructure',
        badge: 'Turnkey Enterprise IT',
        image: '/Corporate%20IT%20Infrastructure%20Setup.png',
        summary: 'Established centralized cloud servers and internal ERP for merged entities.',
        scale: 'Multiple Corporate HQ & Campuses',
        duration: '12-Month Project Lifecycle',
        workforce: 'Senior Infrastructure Engineers',
        impact: 'Centralized Control & Data Security',
        phases: [
            'Site Survey & BOQ Assessment',
            'Structured Cabling & Rack Setup',
            'Cloud Migration & Server Deployment',
            'Network Security & Zero-Trust Framework',
        ],
        states: ['Maharashtra', 'Telangana', 'West Bengal'],
        accent: 'indigo',
        scope: [
            'Turnkey cloud server setup for merged entity data',
            'Enterprise-wide ERP rollout across corporate offices',
            'Network security architecture and perimeter defense',
            'Professional infrastructure audit and stabilization',
            'Zero-downtime infrastructure commissioning',
        ],
        tech: ['AWS Hybrid Cloud', 'Cisco Enterprise Networking', 'ERP Modules', 'Next-Gen Firewall', 'UPS & Power Redundancy'],
        outcomes: [
            'Secure cloud migration',
            'Centralized ERP platform',
            '100% network uptime',
            'Simplified IT governance',
        ],
        category: 'executive',
    },
    {
        id: 10,
        slug: 'pan-india-amc',
        name: 'Pan-India AMC & Technical Support Program',
        shortName: 'Pan-India AMC Support',
        type: 'Managed Services',
        badge: 'SLA-Based Excellence',
        image: '/Pan-India%20AMC&Technical%20Support%20Program.png',
        summary: '24/7 maintenance contract for enterprise and infrastructure clients.',
        scale: 'Nationwide Managed Services',
        duration: 'Multi-year Master Service Agreement',
        workforce: '24/7 Rapid Response Field Force',
        impact: 'Zero Critical System Downtime',
        phases: [
            'Infrastructure Baseline Audit',
            'SLA & Governance Definition',
            'Helpdesk & Monitoring System Setup',
            'Routine & Proactive Maintenance Cycles',
        ],
        states: ['Pan-India Coverage (All States)'],
        accent: 'violet',
        scope: [
            'Comprehensive nationwide maintenance for IT sites',
            'Strict SLA-bound response and resolution times',
            'Active/Passive technical network maintenance',
            'Proactive infrastructure health monitoring',
            '24/7 multi-tier helpdesk and technical field support',
        ],
        tech: ['ServiceNow/Freshdesk ITSM', 'NOC Monitoring Tools', 'Remote Diagnostic Suite', 'Incident Management Framework', 'Mobile Support Ecosystem'],
        outcomes: [
            'Pan-India support desk',
            'SLA resolution (98%+)',
            'Proactive risk prevention',
            'Extended asset lifecycle',
        ],
        category: 'executive',
    },
];

export const detailedProjects = projects.filter(p => p.category === 'detailed');
export const gridProjects = projects.filter(p => p.category === 'grid');
export const executiveProjects = projects.filter(p => p.category === 'executive');

export const accentMap = {
    blue: { pill: 'bg-blue-600', ring: 'ring-blue-500/30', text: 'text-blue-600', bg: 'bg-blue-50', dot: 'bg-blue-600', line: 'from-blue-500 to-indigo-500' },
    indigo: { pill: 'bg-indigo-600', ring: 'ring-indigo-500/30', text: 'text-indigo-600', bg: 'bg-indigo-50', dot: 'bg-indigo-600', line: 'from-indigo-500 to-violet-500' },
    violet: { pill: 'bg-violet-600', ring: 'ring-violet-500/30', text: 'text-violet-600', bg: 'bg-violet-50', dot: 'bg-violet-600', line: 'from-violet-500 to-purple-500' },
};
